fruits=[]
f1=input("Enter the name of the fruit: ")
f2=input("Enter the name of the fruit: ")
f3=input("Enter the name of the fruit: ")
f4=input("Enter the name of the fruit: ")
fruits.append(f1)
fruits.append(f2)
fruits.append(f3)
fruits.append(f4)
print(fruits)
