friends={}
name1=input("EnterFriends name: ")
language1=input("Enter Friends language: ")
friends.update({name1:language1})
name2=input("EnterFriends name: ")
language2=input("Enter Friends language: ")
friends.update({name2:language2})
name3=input("EnterFriends name: ")
language3=input("Enter Friends language: ")
friends.update({name3:language3})
print(friends)
print(friends[name1])
print(friends[name2])
print(friends.keys())
print(friends.values())
print(friends.items())
